name: Deploy to cloudflare pages
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Run-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Deploy application
        uses: cloudflare/wrangler-action@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=prestoui
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: master
